# Generated by Django 5.1.5 on 2025-05-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_delete_lecteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.membre'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.membre'),
        ),
        migrations.AddField(
            model_name='livre',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.membre'),
        ),
    ]
