# Generated by Django 5.1.5 on 2025-05-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_lecteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecteur',
        ),
    ]
